from music_queue import Note

TWINKLE_SONG = [
    "'&=4=R=R=V=V='W=W=f==='U=U=T=T='S=S=b==='V=V=U=U='T=T=c===!",
    "'&====V=V=U=U='T=T=c==='R=R=V=V='W=W=f==='U=U=T=T='S=S=b===!"]

TWINKLE_BPM = 88

TWINKLE_NOTES = [
    Note(4, "C", 4),
    Note(4, "C", 4),
    Note(4, "G", 4),
    Note(4, "G", 4),
    Note(5, "A", 4),
    Note(5, "A", 4),
    Note(4, "G", 2),
    Note(4, "F", 4),
    Note(4, "F", 4),
    Note(4, "E", 4),
    Note(4, "E", 4),
    Note(4, "D", 4),
    Note(4, "D", 4),
    Note(4, "C", 2),
    Note(4, "G", 4),
    Note(4, "G", 4),
    Note(4, "F", 4),
    Note(4, "F", 4),
    Note(4, "E", 4),
    Note(4, "E", 4),
    Note(4, "D", 2),
    Note(4, "G", 4),
    Note(4, "G", 4),
    Note(4, "F", 4),
    Note(4, "F", 4),
    Note(4, "E", 4),
    Note(4, "E", 4),
    Note(4, "D", 2),
    Note(4, "C", 4),
    Note(4, "C", 4),
    Note(4, "G", 4),
    Note(4, "G", 4),
    Note(5, "A", 4),
    Note(5, "A", 4),
    Note(4, "G", 2),
    Note(4, "F", 4),
    Note(4, "F", 4),
    Note(4, "E", 4),
    Note(4, "E", 4),
    Note(4, "D", 4),
    Note(4, "D", 4),
    Note(4, "C", 2)]
